tumblr_key = ""
tumblr_secret = ""
blog_name = "aavestruggler"
phrases = [
    "america ahhs combination",
    "when the cuh is just bussin",
    "she doesn't! big talk w a mf w no fr ugly ass",
    "boring ah hell eclipse",
    "this part is so gang and crazy i like this part",
    "free the house down",
    "all this hate n for what? my body is still coffee period",
    "this reunion did not ate",
    "i'm so gyat period like purr chile on god on cap",
    "i thought the bag was his gyatt for a second",
    "my dms have been hella all day",
    "on blud",
    "i gyatt to find that puppet",
    "why is wally high key low key a fuckass",
    "camo blushin is bussin",
    "what is it finna play",
    "knock 4 gyatt",
    "a fuck ass bob so my hair will always eat",
    "i need that gyat on my dyat",
    "he ate them i'm afraid",
    "she knows she looks tf good",
    "nah you finna dead",
    "this ated",
    "this hella ateing",
    "i know for a fact its finna chewy",
    "these rewards are bussin. no cap. none whatsoever.",
    "bro ong finna make some hella cash",
    "they finna got her",
    "like aren't they ain't embarrassed",
    "a npc dabbing you up is crazy",
    "what the wap is going on",
    "h chile man",
    "stream my liam facecam asf",
    "how to cartoon ah pizza",
    "on cap",
    "delulu rizz friday evening", 
    "down devious side eye",
    "no cap our bakery is high key bussin, such a slay"
]
